import { StyleSheet, Platform } from 'react-native';
import { Colors } from '@/constants/pokemonTypes';

const isWeb = Platform.OS === 'web';

export const styles = StyleSheet.create({
    wrapper: {
        flex: 1,
        backgroundColor: Colors.background,
    },
    loadingFullscreen: {
        flex: 1,
        backgroundColor: Colors.background,
        justifyContent: 'center',
        alignItems: 'center',
    },
    profileHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingTop: Platform.OS === 'ios' ? 54 : 20,
        paddingBottom: 16,
        backgroundColor: Colors.surface,
        borderBottomWidth: 2,
        borderBottomColor: Colors.primaryRed,
    },
    userInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    avatarPlaceholder: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: Colors.whiteAlpha['10'],
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: Colors.primaryRed,
    },
    avatarText: {
        color: Colors.white,
        fontWeight: 'bold',
        fontSize: 16,
    },
    profileSub: {
        fontSize: 11, 
        color: Colors.textSecondary,
        opacity: 0.6,
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    profileName: {
        color: Colors.white, 
        fontSize: 16,
        fontWeight: 'bold',
    },
    logoutButton: {
        backgroundColor: 'rgba(255, 59, 48, 0.15)',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: Colors.primaryRed,
    },
    logoutText: {
        color: '#FF453A',
        fontSize: 12,
        fontWeight: 'bold',
    },
    scroll: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 24,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 16,
        marginBottom: 14,
        marginTop: 22,
    },
    sectionHeaderList: {
        marginTop: 32,
    },
    sectionAccent: {
        width: 5,
        height: 16,
        borderRadius: 2,
        backgroundColor: Colors.primaryRed,
    },
    sectionTitle: {
        color: Colors.white,
        fontSize: isWeb ? 13 : 12,
        fontWeight: '900',
        letterSpacing: 2,
        fontFamily: isWeb ? "'Press Start 2P', monospace" : undefined,
    },
    sectionSubText: {
        color: Colors.whiteAlpha['50'],
        fontSize: 10,
        fontWeight: '700',
        letterSpacing: 0.5,
        marginLeft: 'auto',
    },
    selectedList: {
        paddingHorizontal: 16,
        paddingBottom: 4,
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'flex-start',
        justifyContent: 'center',
    },
    myTeamCard: {
        width: 130,
        height: 125,
        borderRadius: 14,
        borderWidth: 2,
        overflow: 'hidden',
        marginRight: 12,
        ...(Platform.OS !== 'web'
            ? { shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.4, shadowRadius: 6, elevation: 5 }
            : { boxShadow: '0 4px 15px rgba(0,0,0,0.5)' } as any),
    },
    myTeamImageWrapper: {
        height: 75,
        marginVertical: 4,
    },
    myTeamImage: {
        width: 60,
        height: 60,
    },
    outerFrame: {
        borderRadius: 14,
        borderWidth: 3,
        overflow: 'hidden',
        marginBottom: 12,
        ...(Platform.OS !== 'web'
            ? { shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.4, shadowRadius: 6, elevation: 5 }
            : { boxShadow: '0 4px 15px rgba(0,0,0,0.5)' } as any),
    },
    shimmerStrip: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: '40%',
        zIndex: 1,
    },
    innerCard: {
        flex: 1,
        borderRadius: 12,
        overflow: 'hidden',
    },
    innerCardStatic: {
        borderRadius: 12,
        overflow: 'hidden',
    },
    topBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 8,
        paddingVertical: 6,
        borderBottomWidth: 1,
    },
    pokeName: {
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 0.3,
        flex: 1,
        textTransform: 'capitalize',
    },
    hpRow: {
        flexDirection: 'row',
        alignItems: 'baseline',
        gap: 2,
    },
    hpLabel: {
        fontSize: 9,
        fontWeight: '700',
        letterSpacing: 1,
    },
    hpValue: {
        fontSize: 15,
        fontWeight: '900',
    },
    imageWrapper: {
        alignItems: 'center',
        justifyContent: 'center',
        height: isWeb ? 110 : 85,
        marginHorizontal: 8,
        marginVertical: 4,
        borderRadius: 8,
        borderWidth: 1,
        overflow: 'hidden',
    },
    cornerTL: {
        position: 'absolute',
        top: 4,
        left: 4,
        width: 10,
        height: 10,
        borderTopWidth: 2,
        borderLeftWidth: 2,
        borderRadius: 1,
    },
    cornerBR: {
        position: 'absolute',
        top: 4,
        right: 4,
        width: 10,
        height: 10,
        borderBottomWidth: 2,
        borderRightWidth: 2,
        borderRadius: 1,
    },
    pokemonImage: {
        width: isWeb ? 90 : 76,
        height: isWeb ? 90 : 76,
    },
    footerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 8,
        paddingVertical: 6,
        borderTopWidth: 1,
    },
    typesRow: {
        flexDirection: 'row',
        gap: 4,
        flex: 1,
        flexWrap: 'wrap',
    },
    typePill: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 20,
        borderWidth: 1,
    },
    typeEmoji: {
        fontSize: 9,
    },
    typeLabel: {
        fontSize: 8,
        fontWeight: '700',
        letterSpacing: 0.3,
        textTransform: 'uppercase',
    },
    indexNumber: {
        fontSize: 9,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    statsSection: {
        borderTopWidth: 1,
        paddingHorizontal: 8,
        paddingVertical: 6,
        gap: 5,
    },
    statRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    statName: {
        fontSize: 9,
        fontWeight: '800',
        letterSpacing: 0.8,
        width: 35,
    },
    statBarBg: {
        flex: 1,
        height: 8,
        backgroundColor: 'rgba(0, 0, 0, 0.2)',
        borderRadius: 2,
        overflow: 'hidden',
    },
    statBarFill: {
        height: '100%',
        borderRadius: 2,
        opacity: 0.95,
    },
    statValue: {
        fontSize: 8,
        fontWeight: '700',
        width: 22,
        textAlign: 'right',
    },
    glowRing: {
        position: 'absolute',
        top: -2,
        left: -2,
        right: -2,
        bottom: -2,
        borderRadius: 16,
        borderWidth: 1.5,
        pointerEvents: 'none' as any,
    },
    bottomSpacer: {
        height: 24,
    },

    overlayFullscreen: {
        ...StyleSheet.absoluteFillObject,  
        backgroundColor: Colors.background || '#12100E', 
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 9999, 
    },
});